apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-app-3
  labels:
    app: pipeline-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-app-3
  template:
    metadata:
      labels:
        app: pipeline-app-3
    spec:
      containers:
        - name: pipeline-app-3
          image: marianrap/pipeline-app-3:edf2eee
          ports:
            - containerPort: 8080

