apiVersion: v1
kind: Service
metadata:
  name: pipeline-app-3
spec:
  selector:
    app: pipeline-app-3
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # or NodePort if no cloud LB available
